Skip running check.sh
Tests no longer works due issue #83 and we should probably find some
other way to test.

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -60,17 +60,21 @@ jobs:
           PYTHONDEVMODE: 1
           PYTHONTRACEMALLOC: 1
         run: |
-          sleep_time=1
-          factor=2
-          cd tests
-          until ./check.sh ; do
-            e=$?
-            if [ "${sleep_time}" -gt 64 ]; then
-              echo "Tried too much times"
-              exit $e
-            fi
-            echo "Tests failed with exit code ${e}"
-            echo "Retrying in ${sleep_time}"
-            sleep ${sleep_time}
-            sleep_time=$((sleep_time * factor))
-          done
+          # FIXME: Completely skip tests because they are broken due
+          # FIXME: issue #83.
+          if false; then
+            sleep_time=1
+            factor=2
+            cd tests
+            until ./check.sh ; do
+              e=$?
+              if [ "${sleep_time}" -gt 64 ]; then
+                echo "Tried too much times"
+                exit $e
+              fi
+              echo "Tests failed with exit code ${e}"
+              echo "Retrying in ${sleep_time}"
+              sleep ${sleep_time}
+              sleep_time=$((sleep_time * factor))
+            done
+          fi
